### ISSUE TITLE
Image comparison calculation is slow

### ISSUE THREAD

**Issue by chrisfilo** [NeuroVault/NeuroVault#132]
At the moment it takes on average 2s to calculate comparison between to images. We can improve this by:

* storing a downsampled version of each image (we can even extract all values within MNI brain mask for this and store only that)
* performing fewer comparison: for example only with images from collections that have DOIs assigned to them

**Comment by chrisfilo** [comment]
The reduced image representation (fingerprint) could be stored in the database https://docs.djangoproject.com/en/1.7/ref/models/fields/#binaryfield for improved performance.

**Comment by tyarkoni** [comment]
I'd strongly recommend experimenting with saving standardized versions of all images in memmapped arrays for this. There's really not much to it, and it's blazingly fast. See here:

https://github.com/neurosynth/neurosynth-web/blob/master/nsweb/initializers/database_builder.py#L529

It's also easy to drop NaNs and zeros from the target image you're correlating with; e.g., here's the real-time decoding code when a new image comes in (note the option to ignore zeros/nans):

https://github.com/neurosynth/neurosynth-web/blob/master/nsweb/tasks/__init__.py#L111

I think this will also naturally take care of NaNs on the comparison image side, in the sense that if you (a) standardize each image while ignoring the NaNs, and then (b) replace the NaNs with zeros just before saving it to a column in the memmap, then you can safely compute the dot product with the target image and it will have no effect on the correlation (i.e., the NaNs will effectively be ignored).

Doing it this way should let you compare a new image against every other image in something like ~10 secs / 1,000 whole-brain images running on rodeo.

**Comment by tyarkoni** [comment]
One other side benefit is it also becomes very fast (<< 1 second) to slice into any voxel across all studies--e.g., if you want to rank values, or generate a histogram, etc.

**Comment by chrisfilo** [comment]
We definitely need to have a small representation of each map (downsampled to something like 65x65x65, maybe restricted by the MNI brain mask). Our case is a bit different, because the set of maps is dynamic (i. e. new maps get uploaded, some maps get deleted, others get updated) and thus keeping all of them in one file seems problematic. We can however have one small binary file per map and load them when necessary. The problem I'm currently struggling with is how to encode celery task dependencies. Ideally I would like generating each map "fingerprint" to be a separate task. Pairwise similarity calculations are also separate tasks. The problem is that the pairwise similarity task needs the the fingerprint to run. I could not find a nice way to encode this dependency in celery. I could check if the file exists in the similarity calculation task and create it if it doesn't, but since it's a concurrent system I might run into a situation where the file exists, but the writing of it did not finish (although there might be a  way of doing this in an atomic way http://stackoverflow.com/questions/2333872/atomic-writing-to-file-with-python). I could store those "fingerprints" in the database which can have it's own pros and cons. I'm curious what do you think.

Also if we agree on the same format of the map "fingerprint" I could expose it through the API to make decoding even faster.

**Comment by tyarkoni** [comment]
I think storing a subset of voxels in the DB makes sense. It's probably worth doing some systematic experimentation on a variety of images to see what kind of downsampling or subsampling best preserves the correlation structure. As I mentioned earlier, to me it looks like subsampling 20k random voxels does a pretty good job, but I would guess that either downsampling or taking points at regular intervals (e.g., at grid vertices) would do better. Maybe this is somethign @vsoch can look at as part of her project?

WRT the celery thing, I'm not sure. Do you really need the file writing to complete before you compute the correlations? It seems like maybe you could save some I/O overhead and get around the concurrency problem by having the downsampling/subsampling method return the downsampled data array rather than a file handle. Then it wouldn't matter if the file was still being closed in the background.

**Comment by tyarkoni** [comment]
Oh, and yes, I'm happy to agree on whatever fingerprint format you like as long as it's compact and preserves the correlation structure reasonably well.

**Comment by vsoch** [comment]
An experiment to look at different sampling strategies sounds fun :rocket: Here is a quick update of what I'm working on for image comparison, to keep @tyarkoni in the loop:

- I'm first looking at metric robustness to different levels of thresholding (experiment 1, in progress)
- then I'm looking at metric robustness to noise in the data (experiment 2, doing next)
- and for experiment 3 I can assess changes with different sampling strategies

Then we should have a pretty good idea of 1) how much we can/can't down-sample (and a strategy), and how to do the comparisons! 

Given two celery tasks, one to create the image file "fingerprint" and the other to use it to generate the comparison scores, is it too silly to just delay the image comparison metric by some small amount of time to allow the fingerprint to finish, and have the comparison generation task only run when the fingerprint file exists (and as @chrisfilo mentioned above, it could be done by writing to a temporary file and moving when it's finished). It is annoying that we can't have the task for the fingerprint generation to send its data to the image comparison calculation, because all inputs need to fit nicely in json.  What is so terrible about wrapping the generation of the fingerprint and comparisons in the same function (to be run on map upload or update)? It's not ideal, but it would make sure they run in serial. Or we could set max_retries=None for the image comparison (meaning it will try forever) and return a failed state until the fingerprint is detected and the calculation done.  I can think more about this - my brain is in R-mode right now! :wink:

**Comment by chrisfilo** [comment]
On Sat, Feb 14, 2015 at 2:09 PM, vsoch <notifications@github.com> wrote:

> An experiment to look at different sampling strategies sounds fun [image:
> :rocket:] Here is a quick update of what I'm working on for image
> comparison, to keep @tyarkoni <https://github.com/tyarkoni> in the loop:
>
>    - I'm first looking at metric robustness to different levels of
>    thresholding (experiment 1, in progress)
>    - then I'm looking at metric robustness to noise in the data
>    (experiment 2, doing next)
>    - and for experiment 3 I can assess changes with different sampling
>    strategies
>
> Then we should have a pretty good idea of 1) how much we can/can't
> down-sample (and a strategy), and how to do the comparisons!
>
Maybe I can have a stab at this sooner.

>  Given two celery tasks, one to create the image file "fingerprint" and
> the other to use it to generate the comparison scores, is it too silly to
> just delay the image comparison metric by some small amount of time to
> allow the fingerprint to finish, and have the comparison generation task
> only run when the fingerprint file exists (and as @chrisfilo
> <https://github.com/chrisfilo> mentioned above, it could be done by
> writing to a temporary file and moving when it's finished). It is annoying
> that we can't have the task for the fingerprint generation to send its data
> to the image comparison calculation, because all inputs need to fit nicely
> in json.
>
How come?

> What is so terrible about wrapping the generation of the fingerprint and
> comparisons in the same function (to be run on map upload or update)? It's
> not ideal, but it would make sure they run in serial.
>
Yes this can work. Each comparison task will check if each of the two
fingerprint files exist. If not it will create it and use to move file
trick to make the file writing operation atomic (so this way there is no
risk that a concurrent task will read partially written file). We cal
alternatively use https://github.com/NetAngels/celery-tasktree to define
task dependencies.

> Or we could set max_retries=None for the image comparison (meaning it will
> try forever) and return a faile d state until the fingerprint is detected
> and the calculation done.
>
Lets not do that - we can get some jobs stuck forever.

**Comment by vsoch** [comment]
1. That would be awesome!
2. I had thought the default was json, but it [might be pickle](http://celery.readthedocs.org/en/latest/userguide/calling.html#serializers) I remember getting an error when I tried passing actual data that "result not json serializable"
3. Ok :baby_chick:

**Comment by vsoch** [comment]
sort of [like this](https://github.com/celery/celery/issues/1689) I'd need to test it again to re-generate the actual error.  I think we have many options to specify the serializer, so it's probably a non-issue.

**Comment by vsoch** [comment]
Closing issue - comparisons are calculated with a transform, the save is done atomically, and the issue seems resolved!
