### ISSUE TITLE
Some scatterplots don't render if some of the correlations are nans

### ISSUE THREAD

**Issue by chrisfilo** [NeuroVault/NeuroVault#146]
http://neurovault.org/images/compare/1897/76

**Comment by vsoch** [comment]
The issue here was having only one point of overlap for a region. I noticed that the correlation would be a perfect 1 or -1 with 2 points, so I added a check to eliminate regions with < 3 points.  This is an ugly fix for now (a javascript alert box), but it minimally will tell the viewer what is going on! I tested it on my tiny database of 3 images (still working ok) and the two images I downloaded from the link above, and it works in those two cases.

https://github.com/vsoch/pybraincompare/commit/fa79e4c892cee60ad447edfb9a198c9a53b4361b

I'm not going to update the requirements.txt with a new version because there is much still to be done with the package.
