### ISSUE TITLE
find_similar  page improvements

### ISSUE THREAD

**Issue by chrisfilo** [NeuroVault/NeuroVault#148]
* Write the name of the map and collection it belongs to on top
* Dedicate more space for the names of the maps presented

**Comment by vsoch** [comment]
Thinking of a few options for the second point - I have ideas for how to completely redo the page to integrate more filters, but for now slight tweaks seem most appropriate:

![option1](https://cloud.githubusercontent.com/assets/814322/6207667/d40443be-b55c-11e4-9d28-6edd951fa512.png)

1: Adding another line to split image name and collection, and font slightly smaller.  The spacing here is off and the most important information, the score and then image information, seems busy and cluttered.

![option2](https://cloud.githubusercontent.com/assets/814322/6207671/f1a38fb0-b55c-11e4-807b-dee80d88ec62.png)

2: Moving the collection name to the top, because it serves to immediately indicate a grouping. Not much improvement, and the visual balance is only there because the collection name is short. Not simple enough.

![option3](https://cloud.githubusercontent.com/assets/814322/6207673/01880a96-b55d-11e4-87cb-287b399930ba.png)

3: Simplify by removing the collection, and highlighting just the score at the top.

![option3_tooltip](https://cloud.githubusercontent.com/assets/814322/6207679/14cb8e84-b55d-11e4-80d1-67820e6e5fca.png)

It's not obvious to me if there is more value in having the image or collection name.  For one or the other (here the image name) it could be a tooltip for those users looking to find it.  Removed the map type (Z) because this could be easily filtered with tags above.

**Comment by chrisfilo** [comment]
I like option 2 most. I would remove the map type from the thumbnail though. We still need both collection and map names in my opinion.

**Comment by nicholst** [comment]
The thumbnail is great; but two questions:  What happens to negative values (ignored?) and is the color map fixed over all thumbnails?  (I'd suggest keeping it fixed for all; if an image has crazy low/big values, then you want to see it as a yellow/black image right away, and not 'normalised' away the pathology).

**Comment by vsoch** [comment]
@nicholst - the thumbnail is produced with the nilearn ["plot_glass_brain" function](http://nilearn.github.io/auto_examples/manipulating_visualizing/plot_demo_plotting.html). It does not do justice to show negative values - it's really more of a maximally aesthetically pleasing rendition of a statistical map. I haven't dug into these functions beyond testing that the "svg data" is actually png data shoved into an image object. I also haven't yet studied how computer graphics really work other than [communicating with a core library called Cairo](https://github.com/vsoch/pybraincompare/blob/master/compare/atlas.py#L111) to produce basic paths.  I suspect that my curiosity will get the best of me soon enough, and I will look into this. Ideally, we could have a beautiful glass brain that does not normalize away the pathology.

**Comment by vsoch** [comment]
I do think the color is a significant issue - I posted about it to nilearn https://github.com/nilearn/nilearn/issues/455

**Comment by nicholst** [comment]
@vsoch - Thanks for chasing this up. As part of the color scale, I think setting the max manually is also important too, so that in a big panel of these glass brains the colors mean the same thing on all images.

**Comment by vsoch** [comment]
Agreed! I'm going to be doing some work on this - first custom color schemes for different components of image comparison, integration into images that can be static or dynamic, and then "wrappers" to determine the interactivity! This component of the work comes second to the main analyses, however. It will be a lot of fun :smiley_cat:
