### ISSUE TITLE
Improve quality control

### ISSUE THREAD

**Issue by chrisfilo** [NeuroVault/NeuroVault#154]
We need to add two heuristics to check:

* is the map thresholded?
* is the map in MNI space?

This should be done during upload. Users trying to upload a thresholded map or a map that is not in MNI need will will have to check a checkbox that they really want to do that.

Maps not passing the checks will be flagged (with a red banner on top of the image page), but not rejected. Results of the checks will be exposed through the API.

**Comment by tyarkoni** [comment]
What heuristic are you thinking of using? Some minimum cut-off for non-zero, finite voxels within the gray matter MNI mask? Or is there some reliable data in the header that flags this?

Also, maybe we should call this something like a "partial image" rather than "thresholded", because I've noticed there are some images in NeuroVault where it looks like subjects were scanned with a pretty limited field of view. I think it still makes sense to provide the warning about interpreting correlations cautiously in such cases, but we probably want to be agnostic about exactly why the image is missing some data.

**Comment by chrisfilo** [comment]
We cannot use the header for anything - there will be some cutoff. Also good point about the language - maybe we should call them "thresholded/sparse/partial".

**Comment by chrisfilo** [comment]
this is how we can implement warnings in the forms
http://stackoverflow.com/a/15085582/616300

**Comment by vsoch** [comment]
I wrote some preliminary functions (not integrated in NV, but pybraincompare) that will check thresholding and for positive values:

https://github.com/vsoch/pybraincompare/commit/93934fb7630ea4644c8f38379482018d73caf6e0#diff-8b75e362474f4f3a065989d53370c18fR69

@chrisfilo - I modified your function to use a brain mask specified by the user as the "voxels inside brain" - because otherwise the ratio_bad returned was unusually high (> 77%) because it was including all zeros (even outside the brain), and what we want to know is the non-zero inside the brain mask.

Simulated-based testing will be needed to integrate into neurovault (and we can write the functions directly into statmaps/utils.py and not use pybraincompare), but for now I [integrated this into the pybraincompare qa tool report](http://vbmis.com/bmi/project/qa/) so you can look to get a sense for flagged images (eg there are 58 our of 144 flagged).

I also wrote an [example](https://github.com/vsoch/pybraincompare/blob/master/example/estimate_masking.py) of calculating stats from all the Z score maps in NeuroVault.  For the 236 Z score images in NeuroVault, about 45% don't pass threshold of 95% values nonzero with MNI template (FSL) brain mask:

Maps with < 95% non zero in brain mask:
False  True 
  128   108

The mean value is 0.88, standard deviation is 0.18.

For the openfmri studies I am using for my current masking analysis, 144 images, (9 collections in NeuroVault), about 40% don't pass:

Maps with < 95% non zero in brain mask:
False    86
True     58

Mean percentage is higher, 0.93, standard deviation 0.059

I think just knowing the percentages should be enough for my current (last) analysis to say something intelligent about data in NeuroVault with regard to masking strategy... going to work on this more tomorrow! It would be cool to be able to return an estimate of regional masks that were applied, but actually knowing the percent coverage will be useful for the time being.

An attestation that "data in the wild" is more dangerous than "data that we at least originally put in the wild" :wink:

**Comment by chrisfilo** [comment]
I was thinking about using the mask, but I decided against it because it
required resampling of the statistical map (remember they came in different
shapes and sizes). I was worried it would be too slow.

**Comment by vsoch** [comment]
Hmm, I think you might be right though that we should have a solution that can do a calculation without requiring a mask...  I will start to think about this!
