### ISSUE TITLE
count_images_processing should be counting Comparisons not StatisticMaps with transform

### ISSUE THREAD

**Issue by chrisfilo** [NeuroVault/NeuroVault#196]

**Comment by vsoch** [comment]
Ok, so images still processing == comparisons still processing.

The method / query to do this will be akin to [this one](https://github.com/NeuroVault/NeuroVault/issues/134) which I haven't gotten working yet!

**Comment by vsoch** [comment]
I just submit [a commit](https://github.com/vsoch/NeuroVault/blob/update/image_comparison/neurovault/apps/statmaps/utils.py#L466) that will fix this issue. It was almost impossible to do a nested query to the image field "is thresholded" given that BaseStatisticMap is an abstract object. Instead, I did a query to get pks of thresholded images, and then excluded these from the comparison set. I realized that we will need this functionality (likely) more than once, so I wrote functions to:

- count_existing_comparisons
- count_possible_comparisons
- count_processing_comparisons

and get_existing_comparisons, which are used in [find_similar](https://github.com/vsoch/NeuroVault/blob/update/image_comparison/neurovault/apps/statmaps/views.py#L794)

I was thinking - should we have a separate query.py for query functions instead of utils? Given that we will be adding a lot more queries as we do more advanced filtering, etc, it might get kind of crowded in utils.py, and it would be more intuitive to find the functions in query.py.

**Comment by chrisfilo** [comment]
I think those queries will be missing NIDMStatisticMaps which are also
included in comparisons. Counter tests should be made sensitive to such use
case.

**Comment by chrisfilo** [comment]
I don't mind having queries in utils for now.when it grows we can migrate
them

**Comment by vsoch** [comment]
Why is NIDMResultStatisticMap not a type of StatisticMap? What is the difference?

**Comment by chrisfilo** [comment]
NIDMResultStatisticMap has a link to the NIDM metadata file. Both StatisticMap and NIDMResultStatisticMap inherit from BaseStatisticMap. Please send a PR whenever you are ready.
