### ISSUE TITLE
Remove select NIDM from NIDM view

### ISSUE THREAD

**Issue by chrisfilo** [NeuroVault/NeuroVault#369]
It's redundant since the page is suppose to display one NIDM file

**Comment by vsoch** [comment]
Have you thought about a single interface to give access to view all the NIDM in NeuroVault? This would be the reason to have the selection of the files. And likely instead of embedding the json structure for each ttl file into the page, they would be served from the API.

I will, however, remove for the single ttl view - it is just page clutter!

**Comment by chrisfilo** [comment]
Not sure if this is the best place to discuss this, but I am thinking about two new landing pages: "Statistical maps" (standard and NIDM-Results) and "Atlases and parcellations". Those would come with new search interface (to support queries such as "give me all group level maps of n-back task"). Let me know what do you think (I think @tyarkoni would like this since he already mentioned something like this #247).

**Comment by vsoch** [comment]
I think it's wicked! I think this fits nicely with refactoring the "find similar images" view, and it would also make sense to deploy semantic comparison metric with this. Timeline-wise - this would be possible when we can move forward with that analysis.

**Comment by chrisfilo** [comment]
I would keep those things separate (#247, refactoring "find similar images", and semantic comparison). Otherwise we will get one behemoth of a PR. Plus we can split the work.
