### ISSUE TITLE
Server 500 error when deleting a NIDM pack

### ISSUE THREAD

**Issue by cmaumet** [NeuroVault/NeuroVault#583]
Hi NeuroVault's development team! With @AlexBowring, we just got a 500 error when deleting NIDM-Results pack form one of our collections.

The collection in question is http://neurovault.org/collections/2071/. We first deleted a NIDM-Results pack named `spm_0001.nidm.zip` and everything went fine but when we deleted a second pack named `spm_0002.nidm.zip` we got a 500 error:
<img width="1201" alt="screen shot 2017-02-03 at 11 58 39" src="https://cloud.githubusercontent.com/assets/5374264/22590806/ed54d2ba-ea08-11e6-96c6-f822159b1dde.png">

And now, everytime we open the collection (http://neurovault.org/collections/2071/) we get the following warning message:
<img width="579" alt="screen shot 2017-02-03 at 12 05 11" src="https://cloud.githubusercontent.com/assets/5374264/22590824/0cdf24b4-ea09-11e6-86fc-f5be261d6973.png">
and the table remains empty (though the packs inside seem to still be here, e.g. http://neurovault.org/collections/2071/spm_0001_1.nidm).

Could you help us? Many thanks!

**Comment by chrisfilo** [comment]
I'm currently snowed under, but I have invited @AlexBowring to opbeat (@cmaumet is already registered) to gather more debug info: https://opbeat.com/neurovault/neurovault/errors/

**Comment by cmaumet** [comment]
Hi @chrisfilo. Thanks! I have replied on opbeat.

**Comment by AlexBowring** [comment]
Hi @chrisfilo, I just tried signing in to opbeat with my github account but got this error: 

404 - Whoops, page not found.
If someone shared this link with you,
they need to invite you to the organization.

Go back

**Comment by chrisfilo** [comment]
I sent you an invite using your Warwick email. Did you get it? Should I use
a different one?

**Comment by AlexBowring** [comment]
@chrisfilo ahhh yes, just seen it, thank you. I've signed up.

**Comment by chrisfilo** [comment]
I think what might have happened is that NIDM object deletion failed, and left behind some files. I guess then something new with the same name was uploaded and caused a name collision that is causing all the subsequent errors. Can you try to replicate this error on a local dev copy of neurovault and try to see if there is an easy fix?

**Comment by cmaumet** [comment]
@chrisfilo: yes, I think your explanation is right as we indeed uploaded another NIDM pack with the same name (to replace the other one) before deletion. Of course, we are happy to help debugging this but we might have quite a steep learning curve to debug the issue and propose a fix to the NeuroVault codebase... Could we instead try and combine our efforts to more efficiently correct this bug? As a temporary solution, we can create a new collection to hold our data so that we are not relying on this fix for our analyses.

**Comment by chrisfilo** [comment]
Ok. It would be a great help if you could provide (and verify) steps to
reproduce this bug on a local dev instance. This would make fixing the bug
easier for me.

**Comment by vsoch** [comment]
I just hit this bug too! +1 this collection is triggering errors when trying to go in [the interface](http://neurovault.org/collections/2071/) or via the api:

![image](https://cloud.githubusercontent.com/assets/814322/22852587/d06032e4-f00c-11e6-8a99-efdc9975e572.png)

It's probably unfortunately broken in some error state, and may need to be just cleaned up manually. I think it would be very hard to debug on a dev instance, and rationale for not cleaning it up would be to carefully walk though the lines in the view until the error makes total sense. Just taking a peek, here are some suggestions for fixes:

To nip the error in the butt, it would make sense to stop it from happening. I didn't see the original cause, but based on a server error when trying to [delete nidmresults](https://github.com/NeuroVault/NeuroVault/blob/master/neurovault/apps/statmaps/views.py#L398) I think it's likely that the operation was too big to do at runtime, and it quasi completed and returned something in the 500 family to the browser. There are two ways to deal with this - increasing the [timeout of the server](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout), or I think better, making the operation a celery task. I had a similar issue with issuing operations to Google cloud, and the solution I chose was:
- "unpublishing" the object and associated things so that, if some user were to search / query in a way that might lock something, my operation wouldn't bug out. I did this by way of a boolean variable "publish" for the collection that would turn it off in views, etc.
- making the delete a celery task
- (optionally) having a fallback option. This would mean making a copy of things before doing the delete, and then restoring if something went wrong.
- (optionally) using retrying. I really like [exponential backoff](https://pypi.python.org/pypi/retrying) in the retrying library... it's really quite good for anything that requires webby stuffs too, where errors are pretty common. @chrisfilo - I was going to suggest having something like this for the API wrapper too, and maybe [swaggerifying](https://django-rest-swagger.readthedocs.io/en/latest/) it too :)

I put the last two points as optional because I think that the first two, mainly making it a celery task, will resolve the issue.

I made a list of suggestions for ways to change the nidmresults model / functions, but decided that the above would probably be sufficient. If the error is seen again I can definitely look through the code base again and re-think this second line of action.

**Comment by chrisfilo** [comment]
The original error that leads to this broken state was not a timeout but a "Directory not empty". More details here: https://opbeat.com/neurovault/neurovault/errors/240/

**Comment by chrisfilo** [comment]
I have cleaned up the collection on the server (you will have to reupload the missing nidm objects). This, however does not solve the original cause of the problem.

**Comment by vsoch** [comment]
Ah ok! Then what about, instead of a flat shutil rmtree, walking the directory first, changing the permission of each file, deleting, and then deleting the directory as a final step? Then if the error triggers again we would also know the exact file being looped over.

I'd still do the whole shabang with a celery job too.

**Comment by cmaumet** [comment]
I am trying to reproduce this error in a local dev instance but did not manage so far... 

So, I just wanted to confirm whether this issue had been solved in the meantime? If not, I will try again to see if I can reproduce it!

**Comment by chrisfilo** [comment]
That would be great. Thanks!

**Comment by cmaumet** [comment]
@chrisfilo: I did try but unfortunately could not reproduce the error. Can we close this issue and I will reopen one with a more precise description if we get this error again in the future?
