### ISSUE TITLE
Server Error (500) when deleting nidm pack from Neurovault Collection

### ISSUE THREAD

**Issue by AlexBowring** [NeuroVault/NeuroVault#597]
Hi, 

I just tried to delete a NIDM pack spm_0001.nidm from my collection on Neurovault: 
[https://neurovault.org/collections/2488/](https://neurovault.org/collections/2488/)

When I clicked delete I got a page that just said Server Error 500 on it. The nidm pack still exists in the collection and when you click on it it just takes you to the page with the error, at this address: 
[https://neurovault.org/collections/2488/spm_0001.nidm](https://neurovault.org/collections/2488/spm_0001.nidm)

**Comment by cmaumet** [comment]
Hi!

This looks like another occurrence of https://github.com/NeuroVault/NeuroVault/issues/583. 

If you have the possibility to check on the server:

 1. Whether the `spm_0001.nidm` directory is still present
 2. If 1. is `true` whether there are remaining files in the `spm_0001.nidm` directory and if so which files and if they are read-only?

This could help us track this down a bit further as I previously failed to replicate this error on a dev instance.

Thanks!

**Comment by chrisfilo** [comment]
The opbeat error has regressed: https://opbeat.com/neurovault/neurovault/errors/240/
There is also a new one related: https://opbeat.com/neurovault/neurovault/errors/274/

As for your questions:

```
$ tree /efs/images/2488
/efs/images/2488
├── pycortex_all
│   ├── data
│   │   └── __3cb47e137fb71d86_0.png
│   └── index.html
└── spm_0001.nidm
    ├── ContrastExplainedMeanSquare.nii.gz
    ├── FStatistic_pycortex
    │   ├── data
    │   │   └── __3cb47e137fb71d86_0.png
    │   └── index.html
    ├── ParameterEstimate_0002.nii.gz
    ├── ParameterEstimate_0006.nii.gz
    ├── ParameterEstimate_0011.nii.gz
    ├── ResidualMeanSquares.nii.gz
    ├── SearchSpaceMask.nii.gz
    └── spm_0001.nidm.zip

5 directories, 11 files
```

```
$ ls -al /efs/images/2488/spm_0001.nidm/
total 3588
drwxr-xr-x 3 root root    6144 Sep 15 10:49 .
drwxr-xr-x 4 root root    6144 Sep 15 10:56 ..
-rw-r--r-- 1 root root  147235 Jun  7 13:09 ContrastExplainedMeanSquare.nii.gz
drwxr-xr-x 3 root root    6144 Aug  8 01:51 FStatistic_pycortex
-rw-r--r-- 1 root root  151759 Jun  7 13:09 ParameterEstimate_0002.nii.gz
-rw-r--r-- 1 root root  150505 Jun  7 13:09 ParameterEstimate_0006.nii.gz
-rw-r--r-- 1 root root  151406 Jun  7 13:09 ParameterEstimate_0011.nii.gz
-rw-r--r-- 1 root root  303205 Jun  7 13:09 ResidualMeanSquares.nii.gz
-rw-r--r-- 1 root root    3009 Jun  7 13:09 SearchSpaceMask.nii.gz
-rw-r--r-- 1 root root 2742463 Jun  7 13:18 spm_0001.nidm.zip
```

I hope this helps!

**Comment by cmaumet** [comment]
Thanks for the file listing! As discussed on opbeat, it looks like the 'Directory non empty' error can happen with `shutil.rmtree` when the files in the folder to be deleted are read-only (cf. http://stackoverflow.com/questions/26109244/python-shutil-rmtree-throwing-errors). 

Now that we know a bit more about the problem, I will try again to replicate this issue and will get back to you.

**Comment by cmaumet** [comment]
Hi @chrisfilo,

I managed to reproduce the error but only on the production server (sorry!) here are the steps:
 - Create a new **public** collection
 - Upload to your new collection the NIDM-Results pack available at: https://neurovault.org/collections/2488/spm_0001.nidm.zip
 - Delete the NIDM-Results pack
 => Error 500

I am quite convinced that the error is related to the presence of read-only files in this particular NIDM pack. This is a known issue of `shutil.rmtree`. I've proposed a patch in #598 with code from `rmtree` documentation: https://docs.python.org/3/library/shutil.html#rmtree-example.

I am wondering if I did not manage to reproduce the error using the dev version of NeuroVault because it is run in a docker container and therefore with root identity for which read-only permissions do not apply...

Let me know what you think of this update. If you think that's good to go, then it would be great if you can delete the remaining files in `/efs/images/2488/spm_0001.nidm/` and also collection https://neurovault.org/collections/2989/ so that we can start over with a clean state.

Thanks!

**Comment by chrisfilo** [comment]
Thanks for the fantastic investigative work and the patch.

I deployed the fix as well and deleted the requested files and the collection you mentioned.
